services:
  web-service:
    image: web-service
    build:
      context: .
      dockerfile: ./Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /usr/src/app
    environment:
      - GIT_COMMIT_ID=dev
    ports:
      - 8080:8080
