services:
  go-starter:
    image: go-starter
    build:
      context: .
      dockerfile: ./Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /usr/src/app
    environment:
      - GIT_COMMIT_ID=dev
    ports:
      - 80:8080
