name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  TEST_TAG: go-starter:test

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test ./... -v

  build-and-test:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.TEST_TAG }} for testing
        run: |
          docker build -t ${{ env.TEST_TAG }} .

  push:
    runs-on: ubuntu-latest
    needs: build-and-test

    # Only push on main branch push, not PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: WIP
        shell: bash
        run: |
          echo "Not yet pushing to a Docker registry."

      